sudo: required
services:
  - docker

before_install:
  - docker build -t test-image -f Dockerfile.dev .

script:
  - docker run -e CI=true test-image npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "react-docker"
  env: "Reactdocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-297887861797"
  bucket_path: "react-docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

language: generic