version: '3'

services:
  frontend:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4001:3000"
    volumes:
      - app/node-modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node-modules
      - .:/app
    command: ["npm", "test"]